### PR TITLE
Updated README.MD with Debian install instructions

### PR DESCRIPTION
**Pull request by MagicFab**
Added instructions for installation from Debian backports repository.

### CODE REVIEW

**Comment by antenore** [comment]
Thank you @MagicFab I'm merging this and I'm adding you to the contributors

**Comment by antenore** [comment]
Would you mind updating also the main wiki page? Thanks!!!

**Comment by MagicFab** [comment]
I had already updated the wiki page, then later (today) also noticed the README :)

**Comment by antenore** [comment]
Thank you Sir!

**Comment by giox069** [comment]
Thank you! :)

**Pull request merged**
