### PR TITLE
Register and support opening rdp files - Mime improvements

### PR DESCRIPTION
**Pull request by antenore**

### CODE REVIEW

**Comment by BloodyIron** [comment]
Woot! :D

**Comment by antenore** [comment]
Unlucky this won't be available till the next release, except if you compile by yourself or if you install (tomorrow evening) the PPA remmina next daily

**Comment by BloodyIron** [comment]
@antenore well, I'm not dying just yet, hah! But, how often do releases come out for Remmina? What kind of a timeline for the next release is estimated?

**Comment by antenore** [comment]
Usually 3 months. Look at this page to have an idea

https://github.com/FreeRDP/Remmina/releases

It's not a job maintaining Remmina, therefore it happens randomly when we have time.
Has we love Remmina, this is happening quite often considering we are mainly 2 developers plus some spare contributions from time to time.

**Comment by BloodyIron** [comment]
@antenore ahh, well that's still fine for me :) I'll just get this tastyness when it rolls around to my PPA! Thanks for your help and all that! :D

**Comment by antenore** [comment]
Well, I hope it will still work than :-P otherwise come back to me

**Comment by BloodyIron** [comment]
@antenore I'll try to keep that in mind, but no promises! ;) (I may forget by then, hah!)

**Pull request merged**
