### PR TITLE
updated german translation

### PR DESCRIPTION
**Pull request by morph027**
Added german translation for new message strings

### CODE REVIEW

**Comment by antenore** [comment]
Thanks. Is this a replacement for #1020 ?

**Comment by morph027** [comment]
Jip, much more strings included.

**Comment by antenore** [comment]
Ok, so I close that one. Let me know when and if I can merge this one.

Danke.

**Comment by morph027** [comment]
Just do it, if i find more strings, i'll just create another PR. But almost everything is covered right now.

**Comment by antenore** [comment]
Perfect.

**Pull request merged**
