### PR TITLE
FreeRDP software framebuffer

### PR DESCRIPTION
**Pull request by akallabeth**
* Using FreeRDP software drawing functions, removing complexity from remmina
* As a nice bonus all RFX, GFX and GFX-H264 features are working without any change required for remmina (except activating it)
* removes the X drawing primitives previously requires and uses plain GTK
* Added GFX and GFX-H264 settings in GUI.

NOTE: Would be nice if I could get some feedback on possible regressions before a merge.

### CODE REVIEW

**Comment by giox069** [comment]
In 16bpp mode, the address sanitizer terminates remmina with
```
=================================================================
==8516==ERROR: AddressSanitizer: memcpy-param-overlap: memory ranges [0x7fb463528640,0x7fb463528f20) and [0x7fb46352863c, 0x7fb463528f1c) overlap
    #0 0x7fb4825e8ac2 in __asan_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8cac2)
    #1 0x7fb46e5d2eb1 in BitBlt_SRCCOPY_16bpp /home/giovanni/remmina_devel/FreeRDP/libfreerdp/gdi/16bpp.c:163
    #2 0x7fb46e5d5724 in BitBlt_16bpp /home/giovanni/remmina_devel/FreeRDP/libfreerdp/gdi/16bpp.c:828
    #3 0x7fb46e5eb62b in gdi_BitBlt /home/giovanni/remmina_devel/FreeRDP/libfreerdp/gdi/bitmap.c:217
    #4 0x7fb46e6004ce in gdi_scrblt /home/giovanni/remmina_devel/FreeRDP/libfreerdp/gdi/gdi.c:766
    #5 0x7fb46e6c1160 in update_recv_primary_order /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/orders.c:3217
    #6 0x7fb46e6c738e in update_recv_order /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/orders.c:3722
    #7 0x7fb46e733183 in fastpath_recv_orders /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/fastpath.c:205
    #8 0x7fb46e7336ef in fastpath_recv_update /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/fastpath.c:265
    #9 0x7fb46e734ae9 in fastpath_recv_update_data /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/fastpath.c:432
    #10 0x7fb46e73614a in fastpath_recv_updates /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/fastpath.c:563
    #11 0x7fb46e728c14 in rdp_recv_fastpath_pdu /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/rdp.c:1263
    #12 0x7fb46e728cfd in rdp_recv_pdu /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/rdp.c:1271
    #13 0x7fb46e729a34 in rdp_recv_callback /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/rdp.c:1387
    #14 0x7fb46e740c84 in transport_check_fds /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/transport.c:795
    #15 0x7fb46e72a132 in rdp_check_fds /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/rdp.c:1444
    #16 0x7fb46e6c8a64 in freerdp_check_fds /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/freerdp.c:220
    #17 0x7fb46e6c8f36 in freerdp_check_event_handles /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/freerdp.c:262
    #18 0x7fb46eb85342 in remmina_rdp_main_loop /home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:487
    #19 0x7fb46eb8961a in remmina_rdp_main /home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:929
    #20 0x7fb46eb897c8 in remmina_rdp_main_thread /home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:945
    #21 0x7fb4805396a9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76a9)
    #22 0x7fb47f4aceec in clone (/lib/x86_64-linux-gnu/libc.so.6+0x106eec)
```
Usually it happens opening Google Chrome.

This happens also in 24bpp. I was not able to reproduce it in 32bpp. And I'm not able to reproduce it in xfreerdp with /bpp:16 :(

**Comment by akallabeth** [comment]
@giox069 I've rewritten the initialization of freerdp, now using the original command line parser and fixed static channel initialization.
GFX modes are now working and so far I did not have crashes / memory errors with any color depth.

Could you check and confirm?

**Comment by akallabeth** [comment]
Ok, that was fast :/
Looks like the initialization still needs some love, context setup is still screwing up some stuff.

**Comment by giox069** [comment]
Immediate crash from the address saintizer at connection:
```
================================================================
==10774==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000d68935 at pc 0x7fe21dbded95 bp 0x7fe2005704f0 sp 0x7fe20056fc98
READ of size 32 at 0x602000d68935 thread T13
    #0 0x7fe21dbded94 in __asan_memcpy (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x8cd94)
    #1 0x7fe209c8e467 in freerdp_settings_clone /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/settings.c:737
    #2 0x7fe209d0671d in rdp_client_connect /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/connection.c:186
    #3 0x7fe209cc79dd in freerdp_connect /home/giovanni/remmina_devel/FreeRDP/libfreerdp/core/freerdp.c:97
    #4 0x7fe20a1883cc in remmina_rdp_main /home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:885
    #5 0x7fe20a18891d in remmina_rdp_main_thread /home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:931
    #6 0x7fe21bb2f6a9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76a9)
    #7 0x7fe21aaa2eec in clone (/lib/x86_64-linux-gnu/libc.so.6+0x106eec)

0x602000d68935 is located 0 bytes to the right of 5-byte region [0x602000d68930,0x602000d68935)
allocated by thread T13 here:
    #0 0x7fe21dbb476f in strdup (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x6276f)
    #1 0x7fe2093f595e in _strdup /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/crt/string.c:45
    #2 0x7fe20973af06 in freerdp_client_settings_parse_command_line_arguments /home/giovanni/remmina_devel/FreeRDP/client/common/cmdline.c:1666
    #3 0x7fe20a188309 in remmina_rdp_main /home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:878
    #4 0x7fe20a18891d in remmina_rdp_main_thread /home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.c:931
    #5 0x7fe21bb2f6a9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76a9)
```

I think it could be summarized as:
inside client/common/cmdline.c, line 1666, settings->ClientHostname is allocated with a small buffer
  `settings->ClientHostname = _strdup(arg->Value)`
but then, in libfreerdp/core/settings.c, line 737, 32 bytes are required
   `CopyMemory(_settings->ClientHostname, settings->ClientHostname, 32);`

I have exactly the same problem using xfreerdp with `/client-hostname:xxx`

**Comment by giox069** [comment]
I commented out
`argc = add_argv(argc, &argv, "/client-hostname:", g_get_host_name());`
in remmina rdp_plugin.c and the previous crash for ClientHostname has gone away.
But I'm still having memcpy-param-overlap crash as in the previous report.
And the remote image is quite messed up/dirty :(
I'm going to sleep now, I could do other testing tomorrow (central european time :)).

**Comment by akallabeth** [comment]
@giox069 I've fixed the freerdp issue here: freerdp/freerdp#3063 but now running in some other issues. As for your original issue, if I got it correctly this is a undefined ```memcpy``` behavior with overlapping source and destination areas.

**Comment by giox069** [comment]
For the memcpy-param-overlap:
in libfreerdp/gdi/region.c gdi_CopyOverlap() is wrong, because it forgets a pixel at the end of both boxes. Here is a shorter function which seems to give better accurate results:
```
INLINE BOOL gdi_CopyOverlap(int x, int y, int width, int height, int srcx, int srcy)
{
	return (x + width >= srcx && x <= srcx + width &&
		y + height >= srcy && y <= srcy + height) ? TRUE : FALSE;
}
```
This fixes the crash, but I still have screen drawing problems :(

**Comment by akallabeth** [comment]
@giox069 Created pull freerdp/freerdp#3066 to use memmove instead of memcpy just like the 32bit code does.

**Comment by giox069** [comment]
@akallabeth I think the resulting code is a lot confusing in BitBlt_SRCCOPY_32bpp function (and 16bpp version, and maybe 24bpp).
The gdi_CopyOverlap test is wrong.

**Comment by akallabeth** [comment]
yes, fixed the overlap stuff. the bit blit functions are really quite something :/

**Comment by giox069** [comment]
Why don't you just use my working/fixed (I hope :))
```
INLINE BOOL gdi_CopyOverlap(int x, int y, int width, int height, int srcx, int srcy)
{
    return (x + width >= srcx && x <= srcx + width &&
        y + height >= srcy && y <= srcy + height) ? TRUE : FALSE;
}
```
?

**Comment by akallabeth** [comment]
@giox069 Isn't your version including one pixel too much? ```x + width``` is usually outside the rectangle width, whereas ```x + width - 1``` is the last valid point and the CopyOverlay should only check, if source and destination share some memory area.

**Comment by giox069** [comment]
You are right, I really can't remember why 20 mins ago I added "="' to comparisons :( Just wait some minutes, I'm doing further testing.

**Comment by akallabeth** [comment]
@giox069 Just try freerdp/freerdp#3066, should fix that if I didn't fall for the same before coffee off by one ^ ^

**Comment by giox069** [comment]
1. You are right, in my version "=" must be removed.
```
INLINE BOOL gdi_CopyOverlap(int x, int y, int width, int height, int srcx, int srcy)
{
    return (x + width > srcx && x < srcx + width &&
        y + height > srcy && y < srcy + height) ? TRUE : FALSE;
}
```
2. The latesto commit to https://github.com/FreeRDP/FreeRDP/pull/3066 (putting '=') should do the same job. My version is only more "optimized", but I think the compiler will optimize well this version too.

So 1. or 2. are now equivalent. They both don't crash remmina for overlapping memcpy()
You can leave memmove() for paranoid programming reason :)

I'm going to drink my coffee, now.

**Comment by giox069** [comment]
After patching memory problems, I have refresh problem. See video here:
http://s1.casa.panozzo.it/remmina/ak.ogv
(I will remove this post after you will see it :))
Refresh problem happens only moving downward a window's window (chrome, in this case).
If I minimize the remmina connection window and then restore it, a full refresh will make the desktop appear correct. Seems to be a problem in remmina drawing code ?

**Comment by akallabeth** [comment]
@giox069 Just to clear up, the messed up image quality stuff occurs with which settings?
GFX-H264 is buggy with windows 8 and 8.1 (server side ;))

btw, I can't even start remmina when building release without a segfault now :/ (that is also true for branch next) the error seems to be in the rdp plugin (crashes when trying to load) but the debugger does not break in the entry function :/

**Comment by giox069** [comment]
16bpp. Almost all my profiles are 16bpp (I mostly do remote server maintenance with remmina, so I personally don't use GFX).

**Comment by akallabeth** [comment]
@giox069 Ah, ok. Did not see them here, but there is some issue when connecting with win7 (get a crash when accessing freed up memory). 
As for the crash yesterday, well ```make clean``` helps after changing compiler flags ^ ^

**Pull request closed without merging**
