### PR TITLE
Using compact settings for RDP plugin closes Issue 757

### PR DESCRIPTION
**Pull request by antenore**
This pull request improve the Advanced tab check boxes placement to reduce the height of the notebook.

advancetab_compact-view

### CODE REVIEW

**Comment by antenore** [comment]
@giox069 , @weberhofer if you have nothing against this I'm going to merge it.

I'll keep the branch as I want to explore other solution, like an horizontal notebook, instead of the vertical one we have.

I'd like for example to put the profile description on the left and the settings (basic, advanced and SSH) on the right

**Comment by weberhofer** [comment]
Looks very good; regarding the usability, it could be even better to group the checkboxes by functionality: You could at the left side have 
* Ignore cert
* Share Smartcard
* Disable password storing
and the other points, and on the right side
* Redirect mic
* Share local printers
* Disable clipboard sync

From the users point of view, I would (if possible), invert the "Disable [password storing|clipboard sync]" features and per default check them. Deactivating something by activating it is always hard to understand.

**Comment by giox069** [comment]
Looks good. It now fits my old laptop display (1280x800).
I agree, if possible, to change "disable clipboard sync" with "enable clipboard sync" and set it enabled by default in new profiles. Unfortunately we will lose string translations in .po files... but, no problems.

I'm not sure with "Disable password storing" because it was a specific request to have this checbox, a kind of "extra security feature" that the user want explicitly to see.

Ordering: it seems you mean that certificate, password, smartcard all belong to "authentication" and should go together ? Ok, it can be sorted in that way :)

**Comment by antenore** [comment]
Done regarding the order. For the other two options, it's quite cumbersome to make it works correctly.

It's also a bit out of scope compared to this specific issue.

I'm trying to rethink completely the remmina_file_editor and I'll keep in mind these inputs as well.

On the other side, if you have time to improve it go ahead.

I merge this.

**Comment by weberhofer** [comment]
Looks good! I can imagine that including a reverse-logic is much work but it might be good to keep it in mind.

**Pull request merged**
