### PR TITLE
Freebsd support

### PR DESCRIPTION
**Pull request by antenore**
This PR adds support to FreeBSD

@giox069 @weberhofer 

When you have time, can you please test this? ~~(works only with FreeRDP 88fa29c as daylight is not implemented in time.h in FreeBSD)~~ 

To be compiled with -DHAVE_LIBAPPINDICATOR=off on FreeBSD

@akallabeth is aware. ~~I'm also thinking how to solve it~~. Should be fixed by https://github.com/FreeRDP/FreeRDP/pull/3179

### CODE REVIEW

**Comment by antenore** [comment]
Updated PR description

**Comment by antenore** [comment]
@giox069 I'm not sure if the reconnect patch will work (on linux) after this PR, that's why I'm asking to test (try an ssh connection)

**Comment by giox069** [comment]
@antenore: currently the autoreconnect feature only works with non-ssh tunnelled connections.
The lines which sets sockets timeout are only intended to better detect a ssh tunnel timeout/drop, and are not currently related to the autoreconnect feature, and I don't think your modification will break something.
I will test this PR later.

**Comment by antenore** [comment]
Thanks.
I'm aware of it, I was asking because on FreeBSD I've a problem with SSH (after my modifications), even with a normal ssh connection and I was wondering if it was related, somehow to these changes, but effectively is not, I've just tested on Fedora.

**Comment by giox069** [comment]
@antenore: I have tested this PR on Ubuntu, both with and without ssh, and I did a autoreconnect test. All of this is working. Now I'm testing on FreeBSD 10.2, be patient :)

**Pull request merged**
