### PR TITLE
Remmina Main Window Refactoring

### PR DESCRIPTION
**Pull request by antenore**
This PR brings a new Remmina Main window using an header bar

remmina_main

### CODE REVIEW

**Comment by giox069** [comment]
**Gnome Shell screenshot**

client di connessione a desktop remoti remmina_016

**Comment by giox069** [comment]
**Gnome Shell Screenshot**

client di connessione a desktop remoti remmina_016

**Comment by giox069** [comment]
@weberhofer: what do you think of the new remmina main window with restyle menus and toolbar? I like it a lot.
I'm preparing a G+ poll on the G+ community to ask users.
Before merging this PR, someone should test it in a "old packages" distro, like Debian 8.

**Comment by giox069** [comment]
Ok, poll is ready:
https://plus.google.com/communities/106276095923371962010

**Comment by weberhofer** [comment]
Hi @antenore! The refactoring is going in a very good direction, I like it very much - it makes things much easier. I have temporarily switched my openSUSE builds to your branch. It builds and runs without any problems. 

Trying it out, I have found things which could still be improved.

* Pressing <Enter> in the search bar tries to connect to the given address. IMHO most users have their connections stored in a list, so it would be very convenient when pressing <Enter> would automatically open the select (filtered) connection from the list.

* The connection-type drop-down could be placed after the filter-field, which could be followed by a "quick connect" button to be used to connect to the given address using the given protocol (is there a combined select/submit button available in GTK?)

* The "+" button could be moved left to the doughnut-menu-button and the filter/quick-connect related things to the very left of the menu bar.

* The list-related commands (connect, copy, edit, delete) should be available via the drop-down menu only - I don't think they are really needed in the global menu. Also the "new" command could be removed from the menu - the new '+' button is very good and clear to understand.

* From the list-item-context-menu I would completely remove the "external tools" as they are not related to the items at all. The sorting of the items should be "connect", "---", "edit", "---", "copy", "delete") to distinguish more between the types of commands.

All those remarks are only my personal opinion you can think about; You are working great and Remmina is constantly getting better - thank you!

**Comment by giox069** [comment]
> Pressing in the search bar tries to connect to the given address. IMHO most users have their connections stored in a list, so it would be very convenient when pressing would automatically open the select (filtered) connection from the list.
Pressing Enter ? Interesting: I would really benefit for this. But using ENTER for quick connect is important too. It could be done as follow: when, after filtering, only one profile is shown on the filtered list, pressing ENTER on the textbox will connect to that profile ?

I agree with all other @weberhofer's remarks, and add one:
After connecting to a listed profile, remmina updates its .remmina file, but the filtered/sorted list is not automatically refreshed. So during my 2 hours session working for a customer, used profiles does not automatically move at the top of the sorted list. The list of filtered/sorted profiles should autorefresh after each connection. But try to avoid to reparse all profile files when refreshing the list: the slow profile parsing problem is here again in remmina_main: for every key I type, search is very slow.

**Comment by antenore** [comment]
Thanks Johannes,

Here after my comments


* Pressing <Enter> in the search bar tries to connect to the given address. IMHO most users have their connections stored in a list, so it would be very convenient when pressing <Enter> would automatically open the select (filtered) connection from the list.

The <Enter> behaviour is to replace the quick connect feature I've removed, but as you say, hitting <Enter> too early (that is quite instinctive) will try to open a connection with a non existing hosts.
As, while you type, the list is automatically refreshed, the <Enter> key is not needed at all.
What I can probably do, is to open the profile editor if the connection fails (?). 

@giox069 comment:
> when, after filtering, only one profile is shown on the filtered list, pressing ENTER on the textbox will connect to that profile ?

I'm thinking about it. It's not easy and fast for me.

* The connection-type drop-down could be placed after the filter-field, which could be followed by a "quick connect" button to be used to connect to the given address using the given protocol (is there a combined select/submit button available in GTK?)

I didn't understand, sorry, would you mind doing a quick sketch (even on paper)?

* The "+" button could be moved left to the doughnut-menu-button and the filter/quick-connect 
related things to the very left of the menu bar.

I'll try

* The list-related commands (connect, copy, edit, delete) should be available via the drop-down menu only - I don't think they are really needed in the global menu. Also the "new" command could be removed from the menu - the new '+' button is very good and clear to understand.

I agree

* From the list-item-context-menu I would completely remove the "external tools" as they are not related to the items at all. The sorting of the items should be "connect", "---", "edit", "---", "copy", "delete") to distinguish more between the types of commands.

I may be agree but someone, don't remember who, told me that they use the "external tools" to test the connectivity before to use the profile.
In the future I was thinking to add a status column (I already implemented part of it)
remmina_netwrok_monitoring

But this is not easy when using ssh_tunnel and rdp/vnc gateway

@giox069 comments:

> After connecting to a listed profile, remmina updates its .remmina file, but the filtered/sorted list is not automatically refreshed. So during my 2 hours session working for a customer, used profiles does not automatically move at the top of the sorted list. The list of filtered/sorted profiles should autorefresh after each connection. 

This is already done, but at the moment you must move the focus in the quick connect bar.
I don't understand which signal I can use to do it in a better way.

> But try to avoid to reparse all profile files when refreshing the list: the slow profile parsing problem is here again in remmina_main: for every key I type, search is very slow.

I've picked and adapted your patch, so I don't know why it doesn't work, would you @giox069 mind taking a look?

**Comment by antenore** [comment]
Is it better? I personally don't like the menu ""invading"" the desktop space, but is how it works I guess if we put the menu on the right.

xephyr_remmina_newmain_135

**Comment by antenore** [comment]
@larchunix I'd appreciate your opinion if you have some time for us. Thanks!

**Comment by larchunix** [comment]
> I personally don't like the menu ""invading"" the desktop space, but is how it works I guess if we put the menu on the right.

I guess using a GtkPopover instead of a menu might lead to a better result.

> @larchunix I'd appreciate your opinion if you have some time for us. Thanks!

IMHO the overall result is great, although I would have used another layout:
- move the `+` button to the left (as in the first screenshots),
- center the quick connection (combo + entry),
- add a button to switch between tree view and list view just before the menu (and remove the associated items from the menu).

**Comment by antenore** [comment]
Thanks a lot to everybody. I'll do some experiments and come back with some improvements.

@larchunix if you want to join us as an official contributor, you are more than welcome, Remmina would benefit tremendously from your experience, obviously as per your needs/availability and so on, we are a cool (as in freedom) community.

If you want to discuss more about this, just drop us a quick email (git log --> Antenore, Giovanni and Weberhofer ).

**Comment by antenore** [comment]
The GTKHeaderBar is not meant to include complicated layouts, in fact their child components can only be packed at the start or end of the widget.

To have a centered search/quickconnect box I should put  a grid inside the GtkHeaderbar, but IMHO it's too complicated and gross.

As per the Gnome Design Patterns, I should add another bar below the GtkHeader

https://developer.gnome.org/hig/stable/figures/patterns/search.svg 

I'll take some more time to play around this idea that I think it's much better.

**Comment by antenore** [comment]
This adhere more to the Gnome guidelines 

With the Search Bar Deactivated:

selection_145

With the Bar activated.

selection_144

@giox069 , should we update the poll on G+ ?

**Comment by giox069** [comment]
I liked a lot the previous version with the search bar always visible on the first row. Searching, in my daily use, is done very frequently, at each connection. Hiding the search bar is not very useful: I have an extra button shown, I have to unhide it, I lose one line of space. Search, in Remmina, is not an option for me, it's daily life.

If a user does not uses search... he/she could simply ignore it ?

About the G+ poll: we still have too few users and I don't think we will be useful to make a poll now... but it's just another personal opinion. The community is slowly growing, and this is good.

**Comment by antenore** [comment]
> I liked a lot the previous version with the search bar always visible on the first row. Searching, in my daily use, is done very frequently, at each connection. Hiding the search bar is not very useful: I have an extra button shown, I have to unhide it, I lose one line of space. Search, in Remmina, is not an option for me, it's daily life. 

By default is already unhide, hiding the search bar is an option not the standard. So you can consider just the second screenshot.

Regarding the additional row I agree, but I don't have an easy and clean solution to stack it in the middle. We can just have it on the right (end) or on the left (start).

Moreover consider that I've removed completely the window decoration, so you lost one line but you got a new one, so you have lost zero at the end.

I'm undecided, I let you all decide because I really don't know.

Personally I like more this last solution as it is much more "compliant" and easier to code.

**Comment by larchunix** [comment]
> Regarding the additional row I agree, but I don't have an easy and clean solution to stack it in the middle. We can just have it on the right (end) or on the left (start).

When I have suggested to center the quick connect widget I didn't realize it would be this painful. It's not worth it to spend so much effort on it.

**Comment by antenore** [comment]
>  >    Regarding the additional row I agree, but I don't have an easy and clean solution to stack it in the middle. We can just have it on the right (end) or on the left (start).

> When I have suggested to center the quick connect widget I didn't realize it would be this painful. It's not worth it to spend so much effort on it.

Yes, but now I like more this way :-/  is it that bad compared to the first version? 

The design pattern is: https://developer.gnome.org/hig/stable/search.html.en 

Sorry to bother you all guys !!!!  \(ToT)/

**Comment by larchunix** [comment]
I'm fine with the second screenshot (according to the design pattern, the searchbar hide/unhide button should be on the right and the text should be removed).

**Comment by antenore** [comment]
selection_153

Like this should be fine for everybody I think. We just need to fix a weird performance issue.

**Comment by larchunix** [comment]
Well done!

**Comment by giox069** [comment]
Very good!

**Comment by antenore** [comment]
Tested the last @giox069 fixes (thanks!!!).

Everything is fine. I merge this and I'm preparing for a new release.

**Comment by Chugajstyr** [comment]
Previous Remmina main interface is not available now? Any chance it will be accessible as an option? I get used to it))).

**Comment by antenore** [comment]
I'm sorry @Chugajstyr but we cannot support two different interfaces.

Unlucky it's not like desktop theme. The modifications we have done are deep in the code.

We discussed these changes between us and openly with the community before to commit them.

Beside usability reasons and beside the fact that we like a lot this new interface , Gnome is clearly taking this direction in terms of layout and as Remmina is (still? yet?) a GTK+ application we have to follow the wave or one day Remmina won't work and/or integrate in a GTK+ environment.

I understand your discomfort and I'm sorry for this, but we cannot do that much.

Please don't hesitate to open new issues or comment to existing ones, when it makes sense we will do our best to support you.

**Comment by Chugajstyr** [comment]
It`s ok, @antenore, I`am appreciate Your work on improving Remmina, it`s features & usabilty. I too much used to this thing in all, to give up because of the lost toolbar))).

**Pull request merged**
