### PR TITLE
RDP plugin update client main loop to new API

### PR DESCRIPTION
**Pull request by akallabeth**

### CODE REVIEW

**Comment by giox069** [comment]
@akallabeth many many thanks for these patches.
I will merge as soon as possible.
@akallabeth Do you think that some problems reported by users (RDP disconnections, issues #723 #710) were caused by Remmina using the old api ?
@antenore: I checked this PR against the freerdp version on the Ubuntu PPA (december 18 2015) and it seems to be ok. So we could merge.

**Comment by antenore** [comment]
It's fine for me. 
Thanks for the patches!

**Comment by giox069** [comment]
@antenore... never mind. I have problems with input (mouse & keyboard). I will do further testing tomorrow. Maybe we need also an upgrade to freerdp in the PPA.

**Comment by giox069** [comment]
I merged and then readded mouse/keyboard handling with another commit.
Thank you again @akallabeth.

**Comment by akallabeth** [comment]
@giox069 No, I've encountered the disconnects after that too. There also seems to be an issue with the sound channel, I get crashes from time to time (looks like the argument struct is invalid at some point)

**Pull request merged**
