### PR TITLE
Fix english typos as per #1040

### PR DESCRIPTION
**Pull request by antenore**
@DevDef can you please provide more context for the "resolution" typo?

> resolution → definition (resolution is a number of points or pixels per surface unit, i.e DPI and PPI)

Thanks

### CODE REVIEW

**Comment by DevDef** [comment]
In the following strings, for example:

> #: remmina/src/remmina_file_editor.c:460 remmina/src/remmina_pref_dialog.c:79
#: remmina/ui/remmina_preferences.glade:250
msgid "Resolutions"
msgstr ""
> 
>#: remmina/src/remmina_file_editor.c:460 remmina/src/remmina_pref_dialog.c:79
msgid "Configure the available resolutions"
msgstr ""
> 
>#: remmina/src/remmina_file_editor.c:478
msgid "Resolution"
msgstr ""

I think that the correct word is _definition_, like in high definition TV (i.e. number of pixels for a display), not _resolution_. The resolution is the number of pixels per surface unit (i.e. PPI pixel per inch). Though, this is a very current wrong usage of the word resolution…

**Comment by giox069** [comment]
Also: https://en.wikipedia.org/wiki/Graphics_display_resolution
I agree with the fact that "resolution" has the alternative meaning of PPI (and in physics the meaning of resolution is closer to PPI than widthxheight).
But in the last 20 years I have almost never seen a technical document saying "your monitor has a 1024x768 definition". Also try to google for 1024x768 (or 1920x1080) definition and you will find almost nothing which concatenates the two search term.
All documents I have found in my life and I can find on google uses the word "resolution" to describe width and height in quantity of pixels.

**Comment by DevDef** [comment]
All right guys, let it be. ;-)

**Comment by antenore** [comment]
Merging. I've even forgot about his.

**Pull request merged**
