### PR TITLE
More SPICE plugin improvements

### PR DESCRIPTION
**Pull request by larchunix**
Hi,

Here are more improvements for the SPICE plugin:

- Fix a memory leak for the SpiceSession,
- Run the authentication dialog if the password is wrong or missing,
- Add the SPICE protocol to the quick connect list.  

Regards.

### CODE REVIEW

**Comment by antenore** [comment]
Good job, so now spice is in the quick connect protocol list. :-)

**Comment by antenore** [comment]
@giox069 tested and merged

**Comment by antenore** [comment]
@larchunix I had a seg fault, I'm investigating.

I'll open an issue to keep track of it.

**Comment by larchunix** [comment]
@antenore Keep me informed if you manage to reproduce it.

**Comment by antenore** [comment]
On FreeBSD I cannot make it working. 

I attach a core dump just in case, but I don't see a problem in your remmina code but in the spice version that comes with FreeBSD.

[gdb.txt](https://github.com/FreeRDP/Remmina/files/278402/gdb.txt)

At the moment I'll just leave this as reference, what do you think?

**Comment by larchunix** [comment]
Could you try to open a SPICE connection using [vinagre](https://wiki.gnome.org/Apps/Vinagre) on FreeBSD ?

**Comment by antenore** [comment]
Yesterday I've tried with Spicy (the official GTK SPICE client) and it works, I don't know if I can easily try with vinagre because one of it's dependencies is FreeRDP, that on FreeBSD is too old.

I'll try ASAP, meanwhile I open an issue.

**Comment by larchunix** [comment]
If spicy works, it is most likely an issue with my code but I don't have a FreeBSD intallation to figure out where the problem is.

**Comment by antenore** [comment]
I'll take a look as well.
In few days I'll also update the AUTHORS file.

**Pull request merged**
