### PR TITLE
Uzbek Cyrillic: apply latest additions

### PR DESCRIPTION
**Pull request by ozbek**

### CODE REVIEW

**Comment by muflone** [comment]
Merged, thank you @ozbek

**Comment by ozbek** [comment]
Thanks @muflone, but the change has not been reflected on the branch. Is that intentional?

**Comment by muflone** [comment]
whoops, that wasn't intentional, sorry @ozbek 
maybe I closed the pull request without mergeing it before.

Now it was merged by hand.

**Comment by ozbek** [comment]
Thank you! :)

**Pull request merged**
