### PR TITLE
Update da.po (fully translated)

### PR DESCRIPTION
**Pull request by scootergrisen**

### CODE REVIEW

**Comment by antenore** [comment]
Thank you!!!

It'll be available in the next release of Remmina, that will happen in few days as we have to fix an urgent bug.

Can you kindly add yourself in the AUTHORS and in the remmina/ui/remmina_about.glade files? Just add a commit to this PR. If you don't have time I'll do myself.

I'll answer to your issue #1326 ASAP.

Thanks a lot again!

**Comment by scootergrisen** [comment]
I think there is a problem with the translator credits.
Usually in other software there is the msgid "translator-credits" so translators can add them self in the file.

```
#: remmina/src/remmina_about.c:54
msgid "translator-credits"
msgstr ""
"Launchpad Contributions:\n"
"  Joe Hansen https://launchpad.net/~joedalton2\n"
"  Niels Kristensen https://launchpad.net/~nielskri\n"
"  Vic https://launchpad.net/~llyzs\n"
"scootergrisen"
```
But here is says translator_credits in the code already filled in with others names.
Should this perhaps be empty and filled in with the string from above when using danish language?
```
    <property name="translator_credits" translatable="yes">Adolfo Jayme Barrientos &lt;fitojb@ubuntu.com&gt;
Antenore Gatta &lt;antenore@simbiosi.org&gt;
Emmanuel Grognet &lt;emmanuel@grognet.fr&gt;
Giovanni Panozzo &lt;giovanni@panozzo.it&gt;
Jean-Louis Dupond &lt;jean-louis@dupond.be&gt;
Jose Gregorio Jimenez Sanchez &lt;josegjimenez@gmail.com&gt;
Fabio Castelli (muflone) &lt;muflone@vbsimple.net&gt;
Shuhrat Dehkanov &lt;k@efir.uz&gt;
llyzs &lt;llyzs.vic@gmail.com&gt;
Johannes Weberhofer &lt;jweberhofer@weberhofer.at&gt;
</property>
```
Which might be taken from:
```
#: remmina/ui/remmina_about.glade:117
msgid ""
"Adolfo Jayme Barrientos <fitojb@ubuntu.com>\n"
"Antenore Gatta <antenore@simbiosi.org>\n"
"Emmanuel Grognet <emmanuel@grognet.fr>\n"
"Giovanni Panozzo <giovanni@panozzo.it>\n"
"Jean-Louis Dupond <jean-louis@dupond.be>\n"
"Jose Gregorio Jimenez Sanchez <josegjimenez@gmail.com>\n"
"Fabio Castelli (muflone) <muflone@vbsimple.net>\n"
"Shuhrat Dehkanov <k@efir.uz>\n"
"llyzs <llyzs.vic@gmail.com>\n"
"Johannes Weberhofer <jweberhofer@weberhofer.at>\n"
```

In other software they only show the string/names from msgid "translator-credits" for the currently selected language.
So if i use Remmina with danish language i will only see the names of the people that contributed to the danish translated.

**Comment by antenore** [comment]
You are right :-\

Since we took in charge Remmina (3 years ago), we have dealt with translations almost manually. 
There are some contributors that provide us the translated strings after that we generate the files to be translated as per [this](https://github.com/FreeRDP/Remmina/wiki/Update-gettext-messages) procedure.

We would like to put in place something cool and easy to use, or just setup gettext "the right way", but unfortunately we luck the time.

Any kind of help and/or advices are very welcome.

I'll drop the other PR and update myself the Authors.

**Comment by scootergrisen** [comment]
So what are translators suppose to do with the #: remmina/ui/remmina_about.glade:117 string?

**Comment by antenore** [comment]
Till today nothing at all, it's a file I've updated by hand myself at each release.
I've asked you if you could update it because we were preparing the next release.
I don't know if there is an easy way to update it automatically using cmake and gettext.

As you said translators should work only on the po files.

**Comment by scootergrisen** [comment]
I don't know how to write the code i just translate the po file.
I was thinking maybe the AUTHORS fil if only meant for people that write the code and not for translators.
Not that its going to hurt to have like a translator section in the AUTHORS file but maybe its just easier that a translator only have to change one po file and if people want to see who have translated they can look in the po files.

**Pull request merged**
