### PR TITLE
The host key should not affect subsequent key operations

### PR DESCRIPTION
**Pull request by nanxiongchao**
For example, when you use the host key to complete the full-screen mode (ctrl_r + f),
the subsequent key operation has two effects:
Continue to full-screen mode does not need the host key, such as directly
by "f" can be achieved
In the editing interface can not enter other buttons until you press ctrl_r again,
I think this affects the user's experience
I have tested,looks well

### CODE REVIEW

**Comment by antenore** [comment]
Thank you, we are looking at it.

**Comment by antenore** [comment]
Tested, it looks good.
@giox069 I can merge it, ok for you?

**Comment by giox069** [comment]
Looks good for me too.
@nanxiongchao  are you able to squash all the commits in a single commit?  5 commits for a single line of code is a bit... "unbalanced" :)

**Comment by nanxiongchao** [comment]
@antenore Thanks,it's good news for me

**Comment by nanxiongchao** [comment]
@giox069 Thank you for your reminder that I will continue to study and improve

**Pull request merged**
