### PR TITLE
Rename UNIQUE_APPNAME to REMMINA_APP_ID and use it wherever possible

### PR DESCRIPTION
**Pull request by larchunix**

### CODE REVIEW

**Comment by antenore** [comment]
Nice job @larchunix , thanks

**Comment by antenore** [comment]
@larchunix two questions/notes

1) We'd like to make a new release, do you prefer we wait? Do you have anything in progress?
2) If you like/want update the Copyright notice with your name, or just ask, I'll do everywhere adding your name.

**Comment by larchunix** [comment]
@antenore

1. I don't have any pending work for now, you can tag and release a new version anytime you want.

2. To be honest, I don't care about this :). Don't bother yourself adding my name, it's not worth it.

**Comment by antenore** [comment]
@larchunix as you wish :-)

cc @amtlib-dot-dll 

Can you guys update the flatpak on flathub to the last release? 
https://github.com/FreeRDP/Remmina/releases/tag/v1.2.0.30

Thanks!

**Comment by antenore** [comment]
TAG error, sorry

https://github.com/FreeRDP/Remmina/releases/tag/v1.2.30

**Comment by larchunix** [comment]
Done, latest version is now on Flathub.

**Pull request merged**
