### PR TITLE
New release schema

### PR DESCRIPTION
**Pull request by nastasi**
Goal: use a new versioning schema consistent with Launchpad recipes (using LP git instead of bazaar repository). 
1. create locally an official release with managed changelog editing `debian/changelog.in` and checking alignment between `CMakelists.txt` and `debian/changelog.in` files
   
   ```
   $ ./scripts/ubuntu-build.sh
   $ ls -l build-ubuntu/
   remmina_1.2.0~rcgit15e6.orig.tar.gz
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~trusty.dsc
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~trusty_source.build
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~trusty_source.changes
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~trusty.tar.gz
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~wily.dsc
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~wily_source.build
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~wily_source.changes
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~wily.tar.gz
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~xenial.dsc
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~xenial_source.build
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~xenial_source.changes
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~xenial.tar.gz
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~yakkety.dsc
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~yakkety_source.build
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~yakkety_source.changes
   remmina_1.2.0~rcgit16-1ubuntu0~git7839782~yakkety.tar.gz
   ```
2. create locally a development release with automatic `changelog.in` file
   
   ```
   $ ./scripts/ubuntu-build.sh -d
   $ ls -l build-ubuntu/
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~trusty.dsc
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~trusty_source.build
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~trusty_source.changes
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~trusty.tar.gz
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~wily.dsc
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~wily_source.build
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~wily_source.changes
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~wily.tar.gz
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~xenial.dsc
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~xenial_source.build
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~xenial_source.changes
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~xenial.tar.gz
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~yakkety.dsc
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~yakkety_source.build
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~yakkety_source.changes
   remmina_1.2.0~rcgit15e6~dev201609181002-0ubuntu0~git7839782~yakkety.tar.gz
   remmina_1.2.0~rcgit15e6~dev201609181002.orig.tar.gz
   ```
3. on Launchpad
   3.1 have a git repository: [git repo on Launchpad](https://code.launchpad.net/~remmina-ppa-team/remmina-ppa/+git/Remmina)
   3.2 a recipe to build with the same release version syntax [daily recipe on Launchpad](https://code.launchpad.net/~remmina-ppa-team/+recipe/remmina-ppa-git-daily)

### CODE REVIEW

**Comment by antenore** [comment]
Reviewing.

**Comment by antenore** [comment]
I'll test this ASAP on an Ubuntu VM.

My doubts, please comment.

Doesn't this PR make Remmina, one more time, too much Ubuntu oriented?

Is it feasible to move away the debian directory to launchpad?

**Comment by nastasi** [comment]
@antenore it include things to be more easy construct debian/ubuntu packages, nothing to "orient" Remmina, just simplify life to packagers; what is the point ? The code isn't modified or coupled with the debian stuff.

**Comment by antenore** [comment]
> it include things to be more easy construct debian/ubuntu packages,

Nothing against with, and it's cool! Most of our users are on ubuntu, so we are already somehow oriented and that's why we have a PPA.

What I'm sceptic about, is to have distribution oriented files in the main repository as it may:

1) Make people we are strongly oriented
2) Invite other package maintainers  to add their files.

What will happens if also Fedora, Gentoo, FreeBSD, OpenSuSe, Archlinux, (sorry I cannot list all distros here) will ask to add their files in here?

The first issue is that we will have a number of "distro" folders in the Remmina root and the second one is that there will be a lot of job to do every time we will release a new version and also for the nightly builds.

I've probably missed the point, just let me know if I'm wrong.

**Comment by weberhofer** [comment]
I have had a look at the files. IMHO it's good to have distribution related code in a special directory (I could contribute openSUSE related ones), but please do not use ~ in the release names: This does not work in RPM based distributions.

**Comment by nastasi** [comment]
> What will happens if also Fedora, Gentoo, FreeBSD, OpenSuSe, Archlinux, (sorry I cannot list all distros here) will ask to add their files in here?

Good point, an example of what I had in mind:
  - there is a new Remmina release:
  - the official manteiner of distro X updates its fork
  - he/she updates files that need it
  - do the new package for distro X
  - he/she open a PR to us with the changes (that must be in the distro X scope)
  - we review the code and merge it

But we can think about it more, I move the `debian` folder outside in a separated repository.
Stay tuned.

**Comment by nastasi** [comment]
@weberhofer do you have a suggestion for a consistent inter-distro pre-release versioning schema ?

**Comment by weberhofer** [comment]
There are some notes about pre-releases in https://fedoraproject.org/wiki/Packaging:Versioning and https://en.opensuse.org/openSUSE:Package_naming_guidelines;
As RPM orders letters before numbers the alpha, beta and rc tags should not be a problem. I personally like version numbers like 1.1.99.rcgit16 most, as those clearly mark pre-releases to 1.2.0 and shouldn't make issues with all the package managers.

**Comment by diogocp** [comment]
Just drop the rcgit and release the next version as 1.2.0 or 1.2.16. It's been two years since rc1, and each new "release candidate" includes new features.

The distinction between releases and pre-releases is not very useful when you don't maintain a stable branch with backported bug fixes.

**Comment by nastasi** [comment]
I drop this PR, we continue as in the past.

**Pull request closed without merging**
