### PR TITLE
Software drawing v2

### PR DESCRIPTION
**Pull request by akallabeth**
Fixed some issues found in #728:
- Channel cleanup
- Code cleanup to make it easier to read
- Issues found by clang scan-build fixed

### CODE REVIEW

**Comment by antenore** [comment]
@akallabeth wow! 

@giox069 have tested your PR, but due to some libfreerdp issues, it crashes when the address sanitizer is ON, so we must hold on this impressive PR at the moment. 

Would you mind trying to compile both with the address sanitizer and see where the issue is?

Thanks again!

**Comment by akallabeth** [comment]
@antenore I've run this pull with address sanitizer yesterday, what issues do you experience?

**Comment by akallabeth** [comment]
@antenore The only issue I found is freerdp/freerdp#3076 which is currently not merged.
There are some drawing artifacts, but that is a FreeRDP problem and not of your concern at the moment.

**Comment by giox069** [comment]
@akallabeth: I can confirm that without Freerdp PR 3076 the address sanitizer crashes. But now I'm having problems compiling this PR against PR 3076 (missing header file ?)... I need some more time to test.
```
/home/giovanni/remmina_devel/Remmina/remmina-plugins/rdp/rdp_plugin.h:50:29: fatal error: winpr/clipboard.h: No such file or directory
```

**Comment by giox069** [comment]
and @antenore: please don't merge this PR until we have FreeRDP's PR3076 merged AND updated the freerdp on the remmina-next PPA, or we will break remmina on some thousand of machines :)

**Comment by akallabeth** [comment]
As for my changes to ```remmina_rdp_close_connection``` anyone knows a more elegant approach to prevent the dead lock there? Don't really feel comfortable starting a new thread just to clean up resources.

**Comment by antenore** [comment]
Sorry, I've generated some conflicts. Let me know if I can help.

**Comment by giox069** [comment]
Ok, i compiled this PR with https://github.com/FreeRDP/FreeRDP/pull/3076 on another machine and compilation was ok now.
I'm still having garbage on the screen when moving window around the screen. See video here
http://s1.casa.panozzo.it/remmina/ak2.ogv
(I will remove this message from github as usual in few minutes)

**Comment by antenore** [comment]
@akallabeth I'm closing this because the code has diverged too much.
We have the code anyway.
Thanks a lot!

**Pull request closed without merging**
