### PR TITLE
Add OS info for Solus

### PR DESCRIPTION
**Pull request by der-eismann**
Added Solus to the list of OSes for stat tracking.

### CODE REVIEW

**Comment by antenore** [comment]
Ehi @der-eismann thanks a lot!!!! This is very kind and appreciated!

Merging. I'll add you to the contributors ASAP

**Comment by der-eismann** [comment]
You're welcome! I'm not really a maintainer, but I recently built a package for the FreeRDP and Remmina RCs, it should land in the Solus repository shortly. We like new stuff over there :)
Do you plan to publish these statistics?

**Comment by antenore** [comment]
Yes, sure, it won't happen very fast because we didn't write yet the code to parse the json files

**Comment by antenore** [comment]
BTW, would you mind updating the README and the wiki with instructions for solus? Thanks!

**Comment by der-eismann** [comment]
Sure, I'll work on it. Since lots of the new functions are not translated yet, can you tell me how to? This page is not revealing much:
https://github.com/FreeRDP/Remmina/wiki/How-to-translate-Remmina

**Comment by antenore** [comment]
It would be great!

There are 2 issues for the translations

1) The PO files are probably not updated with the last strings

You can update it following the wiki https://github.com/FreeRDP/Remmina/wiki/Update-gettext-messages 

2) It could be in the code there are still not translatable strings.

In this case someone should update those strings. An example of what a translatable string looks like is https://github.com/FreeRDP/Remmina/blob/next/remmina/src/remmina_connection_window.c#L533 except for debug strings, that we prefer to keep in plain (macaroni) English :-) 
You can just simply search for a text that is not in the PO files in the remmina source folders and see if it can easily converted to _("...") or N_("...")

**Pull request merged**
