### PR TITLE
Remmina usage statistics collection.

### PR DESCRIPTION
**Pull request by antenore**
This PR introduce a new module that collects anonymous usage statistics, in order to better target new Remmina features and bug fixing.

All the data collected are meant only to understand how Remmina is used by their developers.

The encryption is done end-to-end on the client side and the user can choose if he/she wants to opt-in or not.

At any moment the users have the power to request to delete all the data we have collected about them.

### CODE REVIEW

**Comment by diogocp** [comment]
Please don't roll your own crypto. Why didn't you use HTTPS?
One immediately obvious weakness of this scheme is that it does not provide forward secrecy, since you always encrypt with the same long-term key.

**Comment by giox069** [comment]
The idea was that the stats are stored encrypted also at the server side and decrypted only at our homes after downloading and deleting them. No private key is stored at the server side. Https is quite useless for this purpose.
Yes, using https in addition to this form of storage protection will also prevent, in case of private key disclosure, a man in the middle observer. But really... is it worth it? This [is what we collect](https://daguniverse.github.io/RemminaDoc/remmina__stats_8c.html#details), no private data. Just the fact that you use or used remmina and your OS info. No username, no hostname, no private data. It's really a few more than a regular cleartext http [User Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) string plus a cookie (UID).
In any case, we could think to add https support in a future release, so if someone opens an issue, I will mark it as ehnancement.
Also if you want to see what your client is sening, enable statistics (on the global preference page), open the debug window and press CTRL+T.

**Comment by giox069** [comment]
Done: https://github.com/FreeRDP/Remmina/commit/bac11a1c843f48dbbfc8730a2ef86d169fa71fb0

**Comment by weberhofer** [comment]
It would be very nice to have a link at the "enable statistics" toolbar which leads to a page on Remmina's homepage that explains in detail which data are collected and when the data are sent.

**Pull request merged**
