### PR TITLE
Make full screen in the same monitor where the connection window reside

### LINKED ISSUE #124: full screen window placement with multiple monitors
When opening fullscreen it opens always on the same monitor fullscreen with a multiple monitor setup and it doesnt matter where the mouse is.

The older version of remmina fullscreen (i belive in ubuntu 10.04 or 09.10) was opening on the monitor where the mouse pointer was.

Is this a bug or is there a different way to choose the monitor for fullscreen?
##

### PR DESCRIPTION
**Pull request by antenore**
This should fix #124 if GTK version => 3.18

Please tests and let me know.

### CODE REVIEW

**Comment by antenore** [comment]
No issues so far, and it seems to work properly, can I merge into 'next'?

**Comment by giox069** [comment]
+1

**Comment by mvdw** [comment]
"Make full screen in the same monitor where the connection window reside"
In some cases, that is the expected behavior, but it is a bad idea in the case where I go from not-full-screen to full-screen.
Please reconsider.
PS: Do you need to choose a monitor in Remmina? I thought the environment has algorithms implemented for that.

**Comment by antenore** [comment]
@mvdw Thanks for your comment, can you please tell me about your specific issue? 
Thanks in advance

**Comment by mvdw** [comment]
No problem. I understand there are many situations. BTW, thanks for the work on Remmina!

I have a laptop at the left with external monitor to the right, openSuse 42.2 KDE plasma5, Remmina 1.2.0 rcgit.13.
If I have a rdp connection with Remmina open, not full screen - completely on the external monitor.
Then I toggle Remmina to full screen mode (with the Remmina button).
What happens next, is that the full screen opens either on the laptop screen, or on the external monitor, depending on the connection window location:
1. Connection window not open - the full screen opens on the laptop (left) - unexpected.
2. Connection window at the laptop screen - the full screen opens on the laptop (left) - unexpected.
3. Connection window open at the right monitor: the full screen opens on the right - expected.

**Comment by antenore** [comment]
Yep, that's a good point.
I think the best is to let the user choose adding an option in the Remmina preferences. Thought it won't be anyway that much flexible as well, but I don't see how it can be done better.

Do you mind to cut and paste this in a new issue? Thanks in advance.
I hope that I'll have time ASAP.

**Pull request merged**
