### PR TITLE
Implemented custom keystrokes for plugins

### PR DESCRIPTION
**Pull request by muflone**

### CODE REVIEW

**Comment by muflone** [comment]
This PR implements a new feature in Remmina.

The user can customize some keystrokes from the preferences dialog
keystrokes-preferences

The keystrokes editor allows some special characters like \t (tab character), \n (enter button), \\ (the \ character itself), \e (escape button).
keystrokes-customize

**Comment by muflone** [comment]
The VNC and the RDP plugins already implemented the feature to forward keystrokes to the plugin window.
keystrokes-vnc

**Comment by muflone** [comment]
Please comment, test and report any issue on this new feature.

**Comment by antenore** [comment]
@muflone I'm testing it right now. So far so good.

I'm looking for some use-cases in my environments, but I think this can be merged.

Any security concerns?

CC: @giox069

**Comment by giox069** [comment]
@muflone: I tested both on Ubuntu 14.10 and Fedora 21 and it works. I did not extensive testing because I cannot find a good use-case :)
About naming: unfortunately I have no better ideas ('keypress sequences' ?). We can rethink it later if needed.
You could merge, but unfortunately you will find some conflicts for automatic merge.

**Pull request merged**
