### PR TITLE
New icons

### PR DESCRIPTION
**Pull request by antenore**
Please let me know what do you sincerely think about this new icon set.

Note that some icons used in the Remmina interface, are the standard GTK icons, therefore they won't match with this specific icon set, unlucky we cannot redesign all the GTK icons. ;-)

@All @giox069 @dktrkranz @Hubbitus @weberhofer @llyzs @awakecoding @repzilon

### CODE REVIEW

**Comment by Hubbitus** [comment]
I personally far from design. So I do not think my mind may be viable in that question...
But at least https://raw.githubusercontent.com/FreeRDP/Remmina/bb009e4f1a3a047e2642b59bbcc3882d93b60fd5/remmina/desktop/48x48/apps/remmina.png is became "traditional", I personaly like it.

**Comment by giox069** [comment]
Here is the result on Ubuntu
selezione_162
I like the new remmina main icon, but not the new smaller "protocol" icons.

Please post other screenshots of other desktops here.

**Comment by antenore** [comment]
remmina_i3

Arch Linux, I don't use a common window manager, this is an i3 session.

To stay politically correct I won't comment.

**Comment by antenore** [comment]
... and MATE

remmina_mate

**Comment by weberhofer** [comment]
This is how it looks like with opernSUSE and gnome 3.14; It looks good, but I would remove the arrows which are shown in the VNC (VNC+SSH) session; it's a bit too much lines.
bildschirmfoto vom 2015-07-16 10 36 49

**Comment by weberhofer** [comment]
The SSH icon replaces the windows icon when having a RDP connection via SSH; this could be improved, too.

**Comment by giox069** [comment]
@weberhofer :+1: the RDP+SSHtunnel icon was better in the past when there was a lock or something similar. Have you any idea on how to graphically show a "ssh tunnel" ?

**Comment by weberhofer** [comment]
@giox069 the +SSH-tunnel symbol was a lock at the bottom-right corner.

If new icons are needed, I'd reduce the lines around the items (make them less visible or remove them) and make the icons more consistent:
* A (local) screen in the lower-left foreground 
* and a remote screen containing the connection's symbol (SSH, VNC etc.) in the top-right background which could be larger than the local one in the front. 
* The tunnel symbol (a lock, or is there something better?) could always be visible as an overlay in the bottom-right corner.

Regarding the icons in the toolbar, I'd leave the old ones, as the symbols for windows and resizing are IMHO very clear and well designed.

**Comment by antenore** [comment]
I'm closing this as we will wait for better icons (if needed)

**Pull request closed without merging**
