### PR TITLE
New gettext strings, closes #1029

### LINKED ISSUE #1029: untranslated lines missed
We support Remmina 1.2+ versions only.
Please do not report bugs occurring on older versions!

Please give us some details about the systems you are using:
* Client (OS name and version): 
* Remmina version (remmina --version): 1.2 rcgit
* Desktop environment (GNOME, Unity, KDE, ..): Unity
* Connecting to (OS and version): 
* Connecting via (RDP, VNC, ...): 
* RDP issues only, freerdp version (xfreerdp --version): 

is needed in addition files po translate new lines.
seleccion_006
seleccion_007

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/38740621-untranslated-lines-missed?utm_campaign=plugin&utm_content=tracker%2F431604&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F431604&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by antenore**

### CODE REVIEW

**Comment by antenore** [comment]
@DevDef @meskobalazs @ozbek @weberhofer @morph027 

Hi All, we have updated the message strings. We'd really appreciate your support if you can.

@weberhofer and @morph027 as you are both German mother tongue, you can probably share some strings?  @morph027 you should probably update your branch with the new messages.

Thanks a lot in advance!
Let me know if you cannot help us this time.

**Comment by morph027** [comment]
Sure, will do ;)

**Comment by meskobalazs** [comment]
Done already: #1032

**Comment by antenore** [comment]
Lovely! Thanks so much!
If not already done, remember me to add your names in the AUTHORS and about page.

**Comment by morph027** [comment]
Your welcome, just being thankful for your great piece of software ;)

If you'd like to add me, real world name is "Stefan Heitmüller" (jeah, Unicode testing ;) )

**Comment by antenore** [comment]
57d1204 here it is.

**Comment by ozbek** [comment]
Done, please see #1037 :)

**Comment by DevDef** [comment]
Salut Antenore !

Here’s the French translation update: [#1038](https://github.com/FreeRDP/Remmina/pull/1038).

And just a few notes about the English strings:
- “succesfully” → successfully
- resolution → definition (resolution is a number of points or pixels per surface unit, i.e DPI and PPI)
- “Transfer complete” →I’d rather say: Transfer completed

Ciao,

Davy

**Comment by DevDef** [comment]
> If not already done, remember me to add your names in the AUTHORS and about page.

As you asked us to mention it, I’m not part of that list…

**Comment by antenore** [comment]
Yes, thanks for having reminded it to me.

**Comment by antenore** [comment]
@DevDef  Done. You are officially part of Remmina, thanks :-)

**Pull request merged**
