### PR TITLE
spice: add support for tls encrypted connections

### PR DESCRIPTION
**Pull request by larchunix**
Please review and test (http://www.spice-space.org/docs/manual/#_tls)

### CODE REVIEW

**Comment by antenore** [comment]
Amazing!

I cannot test this weekend, let's ask Dmitrii if he's available.

Good job!

**Comment by dshcherb** [comment]
I will create certificates and keys via openssl and check if it works with an [XorgQXL](http://www.spice-space.org/page/XorgQXL) instance in a container with the latest patches.

**Comment by dshcherb** [comment]
I have managed to make PKI working for remote-viewer but not for remmina with patches. I am getting the following at the remote side:

Aug 13 19:00:21 testct Xorg[5937]: 139690104429056:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:s3_pkt.c:1472:SSL alert number 48

I added a root CA certificate to the trusted store so it seems strange.

Please _see the following_ for a more detailed list of actions I have done:
https://gist.github.com/dshcherb/9ca58931c3f1af43dc7ec4a15d7a6ce9

With remote-viewer the output is (the full invokation of remote-viewer is _in the gist_):
Aug 13 19:03:11 testct Xorg[5937]: ((null):5937): Spice-Warning **: reds.c:1915:reds_handle_ticket: Invalid password
Aug 13 19:03:14 testct Xorg[5937]: main_channel_link: add main channel client
Aug 13 19:03:16 testct Xorg[5937]: main_channel_handle_parsed: net test: latency 6.377000 ms, bitrate 1982651 bps (1.890803 Mbps) LOW BANDWIDTH
Aug 13 19:03:16 testct Xorg[5937]: red_dispatcher_set_cursor_peer:
Aug 13 19:03:16 testct Xorg[5937]: inputs_connect: inputs channel client create

**Comment by larchunix** [comment]
@dshcherb 

- Remmina SPICE plugin does not support common `spice-gtk` options like `--spice-ca-file` or `--spice-host-subject` (one more thing to add to my TODO list...). Hence, when generating your self-signed certificate, `CN` and remote hostname must match. I.e: in your case, you have to replace `myhostname.example.com` by `10.10.10.247`

- Remmina SPICE plugin's `Server CA Certificate` field is equivalent to `remote-viewer`'s `--spice-ca-file` option. Therefore, you should use `ca-cert.pem`. (Ignore this bullet point if it is the same file as `server-ca.pem`).

BTW, thanks for testing.

**Comment by dshcherb** [comment]
@larchunix 

Thanks! I completely forgot to check the hostname when I generated certificates, so its working now with the regenerated certificates and ca-cert.pem as a "Server CA certificate":

Aug 13 22:59:48 testct Xorg[6640]: main_channel_link: add main channel client
Aug 13 23:00:22 testct Xorg[6640]: main_channel_handle_parsed: net test: latency 11.795000 ms, bitrate 59128 bps (0.056389 Mbps) LOW BANDWIDTH
Aug 13 23:00:22 testct Xorg[6640]: inputs_connect: inputs channel client create
Aug 13 23:00:22 testct Xorg[6640]: red_dispatcher_set_cursor_peer:

Its interesting how for some windows my cursor disappears entirely (e.g. in firefox or libreoffice) while for window borders, menus and system applications it does not (e.g. in nautilus, or system settings). Its unrelated to the pull request and I get the same effect with _remote-viewer_ but if you know how to configure xorgqxl to do better - please do tell.

When I click inside windows and the cursor disappears I constantly get this in the Xorg log:
Aug 13 23:14:38 testct Xorg[6640]: ((null):6640): SpiceWorker-Warning **: red_worker.c:1309:validate_surface: canvas address is 0x7fcc9001faf8 for 834 (and is NULL)
Aug 13 23:14:38 testct Xorg[6640]: ((null):6640): SpiceWorker-Warning **: red_worker.c:1310:validate_surface: failed on 834
Aug 13 23:14:38 testct Xorg[6640]: ((null):6640): SpiceWorker-Warning **: red_worker.c:163:rendering_incorrect: rendering incorrect from now on: handle_dev_update
Aug 13 23:14:38 testct Xorg[6640]: ((null):6640): SpiceWorker-Warning **: red_worker.c:1309:validate_surface: canvas address is 0x7fcc9001ffb8 for 842 (and is NULL)
Aug 13 23:14:38 testct Xorg[6640]: ((null):6640): SpiceWorker-Warning **: red_worker.c:1310:validate_surface: failed on 842
Aug 13 23:14:38 testct Xorg[6640]: ((null):6640): SpiceWorker-Warning **: red_worker.c:163:rendering_incorrect: rendering incorrect from now on: handle_dev_update

**Comment by larchunix** [comment]
@dshcherb 

Sadly, I can't help about your cursor issue.

I use xorgqxl only with the `Xspice` wrapper, hence I never dig into the configuration file.

**Comment by dshcherb** [comment]
@larchunix 

JFYI, I guessed that EnableSurfaces option might affect this somehow. Setting it to False does its magic:
```
   # Enable the use of off screen surfaces
    # defaults to True
    #Option "EnableSurfaces" "True"
    Option "EnableSurfaces" "False"
```

```
grep -RiP 'EnableSurfaces' xserver xf86-video-qxl 
xf86-video-qxl/src/qxl_driver.c:      "EnableSurfaces",           OPTV_BOOLEAN, { 1 }, FALSE },
xf86-video-qxl/examples/spiceqxl.xorg.conf.example:    #Option "EnableSurfaces" "True"
xf86-video-qxl/scripts/Xspice:#Option "EnableSurfaces" "True"

xf86-video-qxl/src/qxl_driver.c:
    { OPTION_ENABLE_SURFACES,
      "EnableSurfaces",           OPTV_BOOLEAN, { 1 }, FALSE },
...
    xf86DrvMsg (scrnIndex, X_INFO, "Offscreen Surfaces: %s\n",
                qxl->enable_surfaces ? "Enabled" : "Disabled");
```

So, as expected, not related to how the spice plugin operates. The warnings in the log are gone now.

**Comment by antenore** [comment]
Good job! I'm merging it.

**Pull request merged**
