### PR TITLE
cmake/FindLIBSSH.cmake: Use Andreas Schneider's (upstream) variant of…

### PR DESCRIPTION
**Pull request by sunweaver**
… FindLIBSSH.cmake.

 The LIBSSH_THREADS library has been dropped in libssh >= 0.8.0.
 This new version of FindLIBSSH.cmake supports that and works against
 recent libssh versions.

### CODE REVIEW

**Comment by sunweaver** [comment]
Ignore the noise. I was working on an old branch if Remmina and that one needed a patch for FindLIBSSH.cmake. The one already shipped on master branch is fine.

**Comment by antenore** [comment]
@sunweaver Thanks a lot for taking the time to look into this.

BTW, we have moved to gitlab since some months in the case you have other PRs (I really hope so ;-) ) 

https://gitlab.com/Remmina/Remmina

Thanks a lot!!!

**Comment by sunweaver** [comment]
Hi,

Am Dienstag, 25. Juni 2019 schrieb Antenore Gatta:
> @sunweaver Thanks a lot for taking the time to look into this.
> 
> BTW, we have moved to gitlab since some months in the case you have other PRs (I really hope so ;-) ) 

Yeah, I just noticed...
 
> https://gitlab.com/Remmina/Remmina
> 
> Thanks a lot!!!

In fact, I jave started yesterday on working on the X2Go plugin for Remmina. I used the work you started some years ago. The X2Go project received some funding to make that happen.

I would actually like to ping you on this later today or this week. The plugin code I have now embeds nicely in pre 1.3.0 Remmina whereas it segfaults after the commit which made the RCW appear before plugin connection. Maybe you have an idea about this.

Mike
-- 
Gesendet von meinem Fairphone2 (powered by Sailfish OS).

**Comment by antenore** [comment]
Cool! This is a really good news!

Well the RCW has been changed quite a lot!

Have a look in the spice plugin as it didn't change a lot since then, it should a matter of the right `git diff`

I'm really interested in helping out, I'm just very busy lately so be patient :-)

If you have a Telegram account https://t.me/Remmina and then if need we can go privately.

Otherwise you have my email in the about widget

**Pull request closed without merging**
