### PR TITLE
Profile and group name niddles in the pre/post commands

### PR DESCRIPTION
**Pull request by antenore**
This patch improve the pre and post commands adding the profile and group name as an additional niddle.

### CODE REVIEW

**Comment by antenore** [comment]
#1485 @AlexGluck  please test if possible

**Comment by AlexGluck** [comment]
How i can build package with this feature and install in fedora 17?

**Comment by antenore** [comment]
I'm going to merge it and than I'll give you the procedure to install it from the main branch.

Do you mean Fedora27?

**Comment by AlexGluck** [comment]
yep, sorry

**Comment by antenore** [comment]
Remove any remmina and freerdp package you have and than follow this

https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20-~-26

Normally just copy&paste from the should work. If you have any issues come back to me

**Comment by AlexGluck** [comment]
Step 2 doesn't work.
I write this batch:
`rpm -qa | grep remmina | cut -f1 -d '1' | rev | cut -f2- -d '-' | rev | while read i; do sudo dnf remove $i; done`

**Comment by AlexGluck** [comment]
Doesn.t work
```
[alexgluck@gluck-laptop ~]$ ls -la ~/remmina.sh 
-rwxr-x---. 1 alexgluck alexgluck 45 фев 27 22:28 /home/alexgluck/remmina.sh
```
```
** (remmina:22070): WARNING **: Command ~/remmina.sh host1 group1 exited with error: Не удалось выполнить процесс-потомок «~/remmina.sh» (no such file or directory)
```
```
** (remmina:22070): WARNING **: Command /home/alexgluck/remmina.sh host1 group1 exited with error: Не удалось выполнить процесс-потомок «/home/alexgluck/remmina.sh» (Нет такого файла или каталога)
```

**Comment by antenore** [comment]
I think you didn't close Remmina after the upgrade. Can you execute the following? 

```pill Remmina && remmina --version```

**Comment by AlexGluck** [comment]
`pill` i cant find
```[alexgluck@gluck-laptop Remmina]$ remmina --version
StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
Running under Gnome Shell version 3.26.2
Remmina - 1.2.0-rcgit-27 (git 6bcd907c)
```

**Comment by AlexGluck** [comment]
```
[alexgluck@gluck-laptop Remmina]$ pkill remmina ;remmina --version
StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed
Running under Gnome Shell version 3.26.2
Remmina - 1.2.0-rcgit-27 (git 6bcd907c)
```

**Comment by AlexGluck** [comment]
in fedora repo remmina version 1.2.0-0.45.20180107.git.d70108c.fc27

**Comment by antenore** [comment]
I saw now the problem, you must write the full path to remmina.sh and not with ~

**Comment by AlexGluck** [comment]
Above I have already written that I tried full path.

**Comment by AlexGluck** [comment]
I'm stupid. Misspelling path after shebang:
```
[alexgluck@gluck-laptop Remmina]$ cat ~/remmina.sh 
#!/usr/binenv bash
echo "$@" >> ~/remmin.log
```

But error output wrong too.

**Comment by AlexGluck** [comment]
Thanks for you help. May be in russian error, sound poor. But basic feature is cool and work properly. I will wait while this feature added in official fedora repos.

**Comment by antenore** [comment]
Spasibo.

If you need more support let me know. May be you can open an issue to the fedora team to update remmina?

Poka.

**Comment by antenore** [comment]
For the error message you see in Russian we can do almost nothing has it's bash that trow out that error.

**Comment by antenore** [comment]
I'm closing this as for me it's solved upstream.

**Comment by AlexGluck** [comment]
[Ticket in Fedora for update.](https://bugzilla.redhat.com/show_bug.cgi?id=1549831)

**Comment by scaronni** [comment]
@AlexGluck new build in updates testing, please test and provide feedback.

**Comment by antenore** [comment]
@scaronni I was in contact with @hubbitus to update the Fedora packages. 

It's great! More over on the last commit, it's just perfect!!!

Do you think is it possible to automatize those builds, at least, at each new official release?

+ eventually having some rights to request a testing build against the last commit?

If you prefer we can speak about this privately.

BTW, have I said THANK YOU! ??? :-)

**Pull request merged**
