### PR TITLE
New plugin with basic support for the SPICE protocol

### PR DESCRIPTION
**Pull request by larchunix**
Hi,

Here is an implementation of a SPICE plugin (requested in #117).

As a first step, only basic features have been implemented.

It has been tested on ArchLinux using `spice-client-gtk3` and the Xspice server from package `xf86-video-qxl`.

Please review.

### CODE REVIEW

**Comment by giox069** [comment]
Hi @larchunix, many thanks for contributing to remmina.

**Compilation**
I can compile this PR on arch, but not under Ubuntu 16.04.
Under ubuntu I installed `libspice-client-gtk-3.0-dev libspice-protocol-dev spice-protocol spice-client-gtk`. CMake output says:
```
-- Finding suggested package SPICE.
--   Disable this using "-DWITH_SPICE=OFF".
-- Checking for module 'spice-protocol'
--   Found spice-protocol, version 0.12.10
-- Checking for module 'spice-client-gtk-3.0'
--   Found spice-client-gtk-3.0, version 0.30
```
But then, compilation fails with
fatal error: spice-client-gtk.h: No such file or directory

Any ideas to fix this and help me compile ? :)

**SSH**
Since the plugin does not support the integrated remmina ssh tunnel (remmina_plugin_service->protocol_plugin_start_direct_tunnel()), you are invited to use that function. Or, as a quick fix, remove the SSH configuration page by zeoring "REMMINA_PROTOCOL_SSH_SETTING_TUNNEL" the in remmina_plugin_spice struct.

**Comment by larchunix** [comment]
Thanks for your feedback.

I have updated the PR:
- conditional include (should fix the compilation issues on ubuntu),
- replaced `REMMINA_PROTOCOL_SSH_SETTING_TUNNEL` by `REMMINA_PROTOCOL_SSH_SETTING_NONE` for now.

**Comment by antenore** [comment]
Thanks a lot @larchunix !!!

**Comment by giox069** [comment]
Merged! @larchunix thank you very much, we will add you to the contributors list as soon as possible.
We also wait for some improvements: for example connection failure and wrong password is not currently detected. It should be detected and reported to the user.
Thank you again.

**Pull request merged**
