### PR TITLE
Update French translation

### PR DESCRIPTION
**Pull request by DevDef**
This is an up to date full French translation containing important fixes on misunderstanding (notably on what is the “host key”) and fixes on French typography rules.

Please, pull it.

Davy

### CODE REVIEW

**Comment by giox069** [comment]
Looks good (but I'm not french :)). @antenore, is it ok ?

**Comment by antenore** [comment]
Parfait, merci beaucoup Davy :-) 

I'm merging it, we'll add you to the cobttibutors list later.

Good, job.

**Comment by DevDef** [comment]
Grazzie mille. :-)
FYI, my name is already mentioned in the list of the Launchpad translators (it’s my second translation of Remmina).
As Remmina is now at version 1.2.0-rc5, may I ask you for an ETA for the final 1.2.0 release, or at least for the next RC (which will ease the import of my translation into the latest distro releases…) ?

Ciao,

Davy

**Comment by antenore** [comment]
Remmina is now at the revision rcgit-15.

Well, the short answer is I don't know :-P

We would like to release the 1.2.0 at the same time as the 1.2.0 of FreeRDP, but I think this it won't happen very soon, so probably we will do it in the next few months. 

I'll add your name in the _official_remmina translator and let you know as soon as we will know.

A++

**Comment by DevDef** [comment]
OK, I understand your position about the release version.
Thank you for these explanations. :-)

Davy

**Pull request merged**
