### PR TITLE
Updated FSF address

### PR DESCRIPTION
**Pull request by weberhofer**

### CODE REVIEW

**Comment by giox069** [comment]
We can merge. Waiting for @antenore and @muflone opinion...

**Comment by antenore** [comment]
OK for me. I cannot merge right now.

**Comment by muflone** [comment]
Some translations are not properly update by this merge and need to be fixed after the merge.
@weberhofer please would you mind to update also the missing translations where the text was partially replaced?

**Comment by giox069** [comment]
@muflone: it seems that the untraslated license @weberhofer left into .po files is no longer in use in remmina_about.c, because the GPL is no longer shown in the about dialog (now there is a link to the website). Can you confirm ?

**Comment by giox069** [comment]
I merged and corrected .po files (removing the unneeded GPLv2 translation). Thank you @weberhofer.

**Pull request merged**
