### PR TITLE
Exit strategy for Gnome Shell 3.26

### PR DESCRIPTION
**Pull request by giox069**
In gnome shell 3.26 the legacyTray (drawer) has been removed,
and there is no place where GtkStatusIcons will be shown.
See
- https://bugzilla.gnome.org/show_bug.cgi?id=785956
- https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/

In this case, remmina must exit when the main window is closed.
This undoes PR #1230, requested in issues #1236 and #1229

### CODE REVIEW

**Comment by nunof** [comment]
Can you not do this until an equivalent alternative exists?
For the same reason Gnome 3.26 still supports status icons with TopIcons* extensions.

Thanks

**Comment by giox069** [comment]
Not possible to undo. Thousand users does not have TopIcons extension installed: if we undo, thousand users will have remmina left running after they close the main windows, with no ways to close it.
The alternative will be to develop appropriate code that detect TopIcons or equivalent tool, test if it is working, do the correct assumptions (i.e. when gnome shell is running  AND gnome shell > 3.26 AND TopIcons is found working) and then avoid exiting. If someone want to develop, test and maintain this code... he/she is welcome.

**Comment by giox069** [comment]
Or install [this extension](https://extensions.gnome.org/extension/615/appindicator-support/). You will have remmina indicators, other apps indicators and remmina will not exit.

**Comment by nunof** [comment]
What I meant was for the proposed behaviour to be applied only to instances started with "remmina -i". My installed version has that option and it seems to me that users that are using that switch are expecting it to outlast the last opened window.

**Comment by nunof** [comment]
Ah, you already support libindicator? Wasn't aware of that, will try it. Thanks

**Pull request merged**
