### PR TITLE
Update es.po

### PR DESCRIPTION
**Pull request by agdg**
Update translations

### CODE REVIEW

**Comment by giox069** [comment]
Ok to merge. Waiting for @antenore and @muflone opinion.

**Comment by giox069** [comment]
Also please note: this is for the "master" branch and will never be imported automatically into the newest "next" branch. @agdg if you like, you can also send a pull request for es.po on the "next" branch, which is a bit different.

**Comment by agdg** [comment]
I saw this version of es.po is older than "next branch" or at least missing some entries.

Maybe it's better not to merge this pull.

**Comment by giox069** [comment]
The master branch is considered "stable", and there are some distributions using it (debian 8). I think we can merge es.po without disrupting its code stability. In the meanwhile, an update for es.po for the next branch will be appreciated, a lot, if you want to help :) I will wait from @muflone and @antenore opinion before merging this pull request into master.

**Comment by muflone** [comment]
I'm for approving this merge into the master branch.
The accelerator must be checked for duplicates but it's not really urgent to do that now.

**Pull request merged**
