### PR TITLE
Customizable app name and locations

### PR DESCRIPTION
**Pull request by 3v1n0**
Allow to customize data locations and app name at compile time.

This allows better snappification of Remmina (and potentially the ability of distribuiting multiple versions togeter, using different app names depending on channels, such as `org.Remmina` and `org.Remmina.Unstable`).
See https://github.com/3v1n0/Remmina-snap.

### CODE REVIEW

**Comment by giox069** [comment]
Tested on ubuntu 16.04 in a development environment, seems to be fine.

**Comment by antenore** [comment]
Tested on Ubuntu 16.04 as well, plus FreeBSD and Fedora 23/24 for compatibility reasons.

Everything is fine. For me can be merged.

**Comment by 3v1n0** [comment]
Thanks, Snap branch (https://github.com/3v1n0/Remmina-snap) updated... Once you want to take ownership for it, just let me know. Also you might want to register the 'remmina' name in the ubuntu store (you can use snapcraft tool or the [apps portal](http://myapps.developer.ubuntu.com/)).

**Comment by giox069** [comment]
Thank you again @3v1n0 , we will proceed as soon as we can.

**Comment by 3v1n0** [comment]
@giox069 no problem...

Let me know in case you'd need help for setting up travis jobs (if you don't want to use launchpad for this) to do automatic uploads on each commit to the edge channel and release tags to the stable one (an example is at https://github.com/elopio/hashicorp-snaps)...

**Pull request merged**
