### PR TITLE
Better button labelling and new save button

### PR DESCRIPTION
**Pull request by antenore**
This patch ad a new "Save and Connect" button and improve the labeling of the others.

See issue #1247

### CODE REVIEW

**Comment by antenore** [comment]
@giox069 I forgot this in the rcgit-20 :-\

Can I merge into "next"? We'll need another release soon

**Comment by antenore** [comment]
Thank you @giox069

**Comment by smilemak** [comment]
@antenore: I tried the remmina in version 1:1.2.0rcgit.21-1 today, and although I can see the new labeling, the settings are saved no matter if I use the "Connect" or the "Save & Connect" button. My report (#1247) was closed because you wanted to follow up in here but it seems that it is still not resolved in rcgit-21?

**Comment by antenore** [comment]
Which setting exactly? All? Because @giox069 has fixed some few days ago, after rcgit-21, a bug regarding the resolution not saved.

**Comment by smilemak** [comment]
Sorry for late reply. When editing a connection and choosing "Connect" button, the settings (e.g. username and screen resolutions) are still saved (basically the purpose of the "Save and Connect" button now). I am fully aware of the commit but my issue #1247  was not solved by it.

**Comment by giox069** [comment]
@smilemak are you running remmina 1.2.0-rcgit.24 ?

**Comment by smilemak** [comment]
@giox069 no still 1.2.0rcgit.22-1. The package is flagged out of date on ARCH so I guess the maintainer will soon update it now. Will reply as soon as tested

**Comment by smilemak** [comment]
@giox069 checked today with 1:1.2.0rcgit.24-1 which works as it should! Thanks a lot!

**Pull request merged**
