### PR TITLE
Added issue-template

### LINKED ISSUE #822: Add a issues-templates to the project
Following all the issues on remmina I have recognized that on so many reported issues important information are missing. There is an feature to add issue-templates which could be very useful. The feature is documented here: https://github.com/blog/2111-issue-and-pull-request-templates

I'd recommend to add such an text like this one to the project:

```
We are supporting Remmina version 1.2+ versions only. Please do not bugs occuring on older versions!

Please give us some details about the system you are using:
* Clients OS:
* Remmina version: 
* Connecting to (OS and version):
* Connecting via (RDP, VNC, ...):
```

@antenore, @giox069 what do you think about that?

### PR DESCRIPTION
**Pull request by weberhofer**
Closes #822. Please merge if ok.

### CODE REVIEW

**Comment by giox069** [comment]
@weberhofer: is there a simple way to test it ?

**Comment by weberhofer** [comment]
I have just activated the issues on my fork: https://github.com/weberhofer/Remmina/issues

**Comment by giox069** [comment]
Tested and it seems almost Ok. Unfortunately I'm not a native English speaker... I could suggest to change
`Please do not bugs occurring on older versions!` to `Please do not report bugs occurring on older versions!`.

**Comment by weberhofer** [comment]
You are right. I'll also ask my wife, who is interpreter, to proof-read.

**Comment by weberhofer** [comment]
The text seems to be ok, so I'll merge.

**Pull request merged**
