### PR TITLE
Removed survey to clean up the code - API CHANGE

### PR DESCRIPTION
**Pull request by antenore**
This PR remove completely the survey and the code used by the survey.

@muflone careful, this PR will change a little bit the API, if you need support let me now.
https://github.com/FreeRDP/Remmina/compare/nosurvey?expand=1#diff-eeaf206ca59e1445d97e45c0a14f68f3

### CODE REVIEW

**Comment by antenore** [comment]
If nobody complains I'm willing to merge this 

@nastasi @giox069 @weberhofer @larchunix

**Comment by antenore** [comment]
I forgot to mention that this remove the  webkitgtk dependency, making the remmina package lighter.

@weberhofer @nastasi I need your go to proceed, in order to avoid packaging issues.

**Comment by weberhofer** [comment]
I'll remove the dependencies as soon as you have committed. Thank you for notification!

**Comment by antenore** [comment]
I'm waiting the PR of Giovanni concerning the freerdp update.

**Comment by nastasi** [comment]
I create a "-debian"  repository branch compainion to remove the dependency mentioned above.
Compiled without troubles.
https://code.launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-nosurvey-ppa

**Comment by giox069** [comment]
@antenore: merge this ASAP. Later, this night, I will PR & merge libfreerdp_updates, and then notify major maintainers.

**Comment by antenore** [comment]
Cool!

**Pull request merged**
