### PR TITLE
Fix russian translations as per #1070

### PR DESCRIPTION
**Pull request by antenore**
@IgorFilth PLease comment on this. Do you think we can live with my mistakes or can we wait for a new Remmina release (at least 3/4 weeks)?

@nastasi @giox069 Should I submit a new release?

### CODE REVIEW

**Comment by giox069** [comment]
I don't think we need a new release for non urgent fixes :) We will have all the translations updated in the next release. Usually in one or two months.

**Comment by antenore** [comment]
Ok, so I'll just merge as soon as Igor will confirm everything is fine.

**Comment by IgorFilth** [comment]
I confirm. Everything is fine now.
Yes, we can wait for a new Remmina release.

**Comment by antenore** [comment]
Thanks, I'll add you on the contributors list.

**Pull request merged**
