### PR TITLE
flatpak: add manifest for flatpak-builder

### PR DESCRIPTION
**Pull request by larchunix**
I have tested NX, SFTP, SPICE, SSH, VNC and XDMCP plugins and  I have not noticed major issues.

RDP basic functionalities (keyboard, video, mouse) work fine but I did not try advanced features.

Smart card support is not enabled for now (I don't have any smart card reader to test).

Please test and merge if interested.

### CODE REVIEW

**Comment by antenore** [comment]
Really cool! This is somthing that must be added in the wiki and in the README.
I'll test and merge it ASAP

**Comment by antenore** [comment]
Do I merge or do you prefere to do it yourself?

**Comment by antenore** [comment]
@giox069 try it if you can, it's quite amazing :-)

**Comment by larchunix** [comment]
@antenore: Please do so.

**Pull request merged**
