### PR TITLE
Fix GTK+2 build failure

### PR DESCRIPTION
**Pull request by heptalium**

### CODE REVIEW

**Comment by antenore** [comment]
@giox069 
Thx Gio

**Comment by giox069** [comment]
??? io ho solo premuto il bottone "merge"... ringrazia heptalium :)

Il 06/05/2015 22:41, Antenore Gatta ha scritto:

**Comment by giox069** [comment]
I just pressed the "merge" button, thank you to @heptalium

**Comment by antenore** [comment]
Rofl. You usually are the brain and me the hand, that's why I've the habit to tell thanks to you.
So thanks to both

**Pull request merged**
