### PR TITLE
Office software reflect slowly to copy or cut text

### PR DESCRIPTION
**Pull request by nanxiongchao**
In the use of word or excel to copy or cut operation, often slow response, but this phenomenon seems to exist only in office software, Notepad test is normal.
Checking the “Disable clipboard sync” in the Remote Desktop Settings dialog box can solve this problem, but it has lost some functionality.
In the commit, the waiting time is changed to 0, you can see the reaction is faster at the same time in the test did not find the introduction of other obvious effects, not entirely clear why the default is set to 2, whether there is a special role.
Perhaps this is not the best solution, what other people's advice or whether to provide a better solution.

### CODE REVIEW

**Comment by nanxiongchao** [comment]
The last commit 293ff8d is valid, ignoring the other

**Comment by antenore** [comment]
Thanks @nanxiongchao 

I'm testing

**Comment by antenore** [comment]
@nanxiongchao I've sometimes issues when the clipboard object is too big, that is the reason why @giox069 have set the default to 2.

The best, probably, is to make this a configuration option? 

Unlucky I cannot accept this PR as it can break most use cases.
I hope you don't mind and that you are available to help us to find a better solution.

I'll leave this opened waiting for your and Giovanni' comments.

**Comment by sh-dvl** [comment]
well, we also have problems with Excel 2010 when clipboard-sync is active
unfortunately we must have a possibility, to copy text from windows to linux.
maybe it's possible, to 
- filter clipboard to only sync, if the entry is pure text and not any object
- maybe do uni-directional copy/paste, because we think that's not the problem copying the object from Windows to Linux, but which then happens with that object... (we can't test it without having an option for it)

**Pull request closed without merging**
