### PR TITLE
Fix a bunch of memleaks

### PR DESCRIPTION
**Pull request by jviksell**

### CODE REVIEW

**Comment by antenore** [comment]
Thanks for the pull request, we'll take a look after vacations

**Comment by antenore** [comment]
I'm testing it.

**Comment by antenore** [comment]
@jviksell Thanks for the good job.

I'll tag a new version and add you to the contributors list in the next days.

I was wondering if you used any tools (and how) in particular to catch the memory leaks, because with what we use we didn't find these ones.

Thanks again!

**Comment by jviksell** [comment]
Thanks!

I used Alleyoop. (which uses Valgrind)

**Comment by antenore** [comment]
Here you go https://github.com/FreeRDP/Remmina/releases/tag/1.2.0-rcgit.8

Welcome on board and I really hope you will contribute again to the project.

Thanks!

**Pull request merged**
