### PR TITLE
snap: Updated to use core18 and gnome-3-28-1804

### PR DESCRIPTION
**Pull request by kenvandine**
* Updated to use core18 and gnome-3-28-1804.  Also refactored a bit.
* stage libssh rather than building it as a part
* Moved some non-snap files to snap/local
* Moved non-snap files to snap/local to keep snapcraft from complaining

### CODE REVIEW

**Comment by antenore** [comment]
Amazing! Thanks a lot!

Just a small issue, we have moved the Remmina project on gitlab, unfortunately we cannot disable PR here.
Do you mind submitting the MR on gitlab?

Otherwise how we can do to keep your ownership?


Thanks thanks thanks really!

**Comment by antenore** [comment]
Forgot to menton the URL.
https://gitlab.com/Remmina/Remmina

**Comment by kenvandine** [comment]
No worries, I'll submit it on gitlab.

**Comment by kenvandine** [comment]
I've submitted this PR on gitlab

**Pull request closed without merging**
