### PR TITLE
Review and fix fullscreen toolbar. Improve Remmina instance management on system.

### PR DESCRIPTION
**Pull request by jalopezsuarez**
I order to minimize the toolbar with less functionality in order to avoid users to change options and focus only on RDP fullscreen connection.

### CODE REVIEW

**Comment by antenore** [comment]
Hi Jose,

thanks for the PR.

I was wondering why you have removed the full screen button, that's not an option but an action icon, if you remove it, users won't be able to switch to full screen... Or maybe am I missing something?

The other commits looks good, give us some time to test and let us know your point about the full screen

Thanks again!

**Comment by jalopezsuarez** [comment]
Hello,

the point about to minimize the toolbar in fullscreen mode, is because of my scenario. I am using Remmina on a ThinClient based on Debian Raspberry Pi 3 terminals.

I wanted to have all the control and prevent users to change everything, just click on an desktop icon, launch remmina with -c command and show their remote virtualised desktop for each user. In my company I am working to virtualize everything and change all computers and install raspberry as thinclient with remmina.

The thing is, depends of the scenario in some cases is useful to have all the original icons and functionalities on toolbar fullscreen, but in other cases is necessary to limit access to this, in the same way I can clear all keyboard commands in settings, change it and clear if I want for limited users. 

It would be perfect to have the ability to choose what icons I want to put on the Connection Window Toolbar (fullscreen or not), in order to limit o allow full access to all funcionalitys (switch between fullscreen, exit without close session...)

So thats the point about the toolbar.

Thanks!

**Comment by antenore** [comment]
I see your point and it's interesting, but it's indeed better to give the choice to the user whenever they want or not to show some icons.

If you are up to it it would be good to have a new tab in the remmina_pref_dialog.c with a checkbox for each icon.

Regarding the "remmina quit", on i3wm, when I quit the remmina_file_editor window and there is an already opened connection, nothing happens. How is implemented by your PR, we risk to receive some bug request because the Quit command does not work.

Some good behaviors would be:

- Show a popup saying Remmina cannot be closed because there are opened connections.
- Otherwise minimize the remmina_file_editor.
- Otherwise, but this is quite complex, change completely the forking/threading model of Remmina.

Ideally is better to split this PR in two different ones, but at the moment we can keep this opened for discussion. As soon as @giox069 will have some time will comment with his thoughts as well.

Please keep working on this, we are interested and thanks a lot for your support.

**Comment by antenore** [comment]
@jalopezsuarez Can I've your comments about my last reply? 
If you want to discuss it further you can contact me and Giovanni by email (see the about widget in Remmina)

**Comment by antenore** [comment]
@jalopezsuarez we have to close this as we want a different approach.
Better to create an issue and discuss over there the possibilities.

**Pull request closed without merging**
