### PR TITLE
Adds monochrome tray icons

### PR DESCRIPTION
**Pull request by wa4557**
This is how it looks like with Adwaita icon theme (standard ghome icon theme)
screenshot from 2016-06-13 09-33-22

and ubuntu-mono-dark
screenshot from 2016-06-13 09-33-43

### CODE REVIEW

**Comment by antenore** [comment]
OMG it's cute! :-)  You can post it on r/unixporn.

I'll test and post my screenshot as well

**Comment by antenore** [comment]
On a standard Xfce4 it's almost invisible (sorry, my setup is quite ugly)

xfce4_remmina_monochrome

**Comment by antenore** [comment]
on i3wm, my personal setup, it's very nice, it makes the other icons awful :-)

i3wm_remmina_monochrome

**Comment by antenore** [comment]
Cinnamon 

cinnamon_remmina_monochrome

Ok for me.

**Comment by wa4557** [comment]
Well the downside of light monochrome icons is that they don't work on light panels

**Comment by antenore** [comment]
We are thinking to a fall-back for those who have a light theme.
Meanwhile for me it's a go! I'd also update the main logo icon with the same icon you used (but the blue one).

Let's see the comments of the other comrades.

**Comment by antenore** [comment]
@weberhofer @larchunix @giox069 

What do you think? In my opinion we can go with this one.
I'll just double check, as it should be the case, that a different icon can be provided by a theme.

**Comment by larchunix** [comment]
I'm fine with it.

**Comment by weberhofer** [comment]
Sorry for the late response. Currently I don't have much free time for everything. I like the new icon and think, that also the start-icon should be replaced by the new one.

**Comment by giox069** [comment]
Approved! 👍

**Comment by antenore** [comment]
Ok, so I'll update this PR with the default Remmina icon, using the Blue Logo and then I'll merge.

**Pull request merged**
