### PR TITLE
Prior Connection Command

### LINKED ISSUE #553: Prior connections commands are executed in background
Reported in the #520 issue by @BrainwreckedTech 

> The only problem is that VNC connection is attempted immediately after and is given no timeout. This > results in an immediately failure for the VNC connection. The command execution part works as expected, though.

The command should be executed in foreground with eventually a timeout

### PR DESCRIPTION
**Pull request by antenore**
A command that can be executed just before any connection.
Fixes #553 , requested in the #520 issue by @BrainwreckedTech

Can you please test/destroy/critics and let me know?

@giox069

### CODE REVIEW

**Comment by BrainwreckedTech** [comment]
AWESOME!  This works.

I noticed is that I needed to specify full paths.  For me, that's an, "Oh well."  But along with I think I ran into a text entry limit when editing the command.

I don't know where the logic error lies in this next one.

The proper command (the one that works as expected) is:

/usr/bin/sudo /scr/qcl -w -x 50 -m 512 -p /mnt/qvm/clib-arch.img -t /usr/bin/konsole

But when I try:

/usr/bin/konsole "/usr/bin/sudo /scr/qcl -w -x 50 -m 512 -p /mnt/qvm/clib-arch.img"

I get the old, dreaded, immediate, "VNC connection failed."  What's expected is that the command should wait up until the timeout because konsole isn't going to exit.  The same goes for xterm.

Konsole fails with:

QCoreApplication::arguments: Please instantiate the QApplication object first
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.

Xterm fails with:

/usr/bin/xterm: No absolute path found for shell: /usr/bin/sudo /scr/qcl -w -x 50 -m 512 -p /mnt/qvm/clib-arch.img

**Comment by antenore** [comment]
Thanks for the test. Let me take a look and I'll fix it.

**Comment by antenore** [comment]
Just a note... Considering my dev skills, this is a quite big amount of job to do for me.
In the meanwhile try to put your commands in a shell script, it should work.

**Comment by antenore** [comment]
@BrainwreckedTech 

I've done some improvements.

- Tooltip
- Search path (it uses PATH environment variable)
- Even if the command is not valid, remmina willl try to start the connection (it must be this way IMHO)

**Pull request merged**
