### PR TITLE
French translation update and other po files update with new strings to be translated

### PR DESCRIPTION
**Pull request by DevDef**
Ciao Antenore,

Here’s a pull request with:
- all new gettextized strings extracted and merged into all po files (so that translators just have to pick up their respective file and update it);
- a replacement of a gettext() call by a ngettext() to correctly handle the plural form(s);
- a typo fix;
- and my updated French translation.

Regards,

Davy

### CODE REVIEW

**Comment by giox069** [comment]
Great! Thank you.

**Comment by DevDef** [comment]
You’re welcome!
Thank you for all the good work Giovanni.

Ciao,

Davy

**Comment by antenore** [comment]
Ciao Davy!

Merci beaucoup!

I'm merging this right now.

**Comment by DevDef** [comment]
Grazie mille. :-)

Ciao,

Davy

**Pull request merged**
