### PR TITLE
fix regression introduced by 190ea2f98ab0443b8a05f70c79e2af037f9fca94

### PR DESCRIPTION
**Pull request by zfil**
See issue #616

### CODE REVIEW

**Comment by giox069** [comment]
@zfill and @lanoxx, unfortunately we have no means (and no time) to check in advance what will happen to the PPA before committing/merging here on github.
So my idea is to merge this fix and see tomorrow what it will happen to the PPA. @antenore, do you agree ?

**Comment by antenore** [comment]
Yes, but I'm rolling back the pull request as I'm not sure tomorrow I'll have time to revert it again.
It's really weird what happens by the way. I cannot get why @bindir@ is not expanded...

**Comment by antenore** [comment]
Ah! Sorry didn't read carefully...

Yes! Also because this is quite the same modification I proposed to @lanoxx 

So, let's try, but as Giovanni said we cannot guarantee it'll work before tomorrow (but I'm confident)

**Comment by antenore** [comment]
That's it

**Comment by giox069** [comment]
Thank you. Let's see what will happen to the PPA tomorrow :)

**Comment by giox069** [comment]
And thank you to @zfil and @lanoxx too :)

**Comment by antenore** [comment]
Yes, thanks :-P !

**Pull request merged**
