### PR TITLE
Add descriptions for some freerdp exit status code

### PR DESCRIPTION
**Pull request by giox069**
@antenore: I added 4 new text strings for these errors. Can you have them reviewed by a English mother tongue technician ?

### CODE REVIEW

**Comment by antenore** [comment]
Sure.

**Comment by antenore** [comment]
They are perfect. Do I merge? Do you have anything to add?

**Comment by giox069** [comment]
I will add "is", but check also for "has expired" vs "is expired". Which one ?

**Comment by antenore** [comment]
In general, you should use "to be" or "to have" in accordance of the first verb in a sentence, for example:

> I have checked and the account has already expired (has -> has). 

Another thing is that "is expired"  implies a long-standing condition (The account is expired sine 2 years), "has expired" a recent change in the state (the account has just expired).

So, "is expired", as we don't know when, should be the most appropriate. Than I don't think we have several Oxford users to care so much in this case ;-)

Go for "is expired", "is locked out" etc.

Thank you Sir. Beckett!!

**Comment by giox069** [comment]
@antenore: it should be fine to merge now.
This patch adds 4 possible error return code from libfreerdp. But not all four seems to be currently implemented inside libfreerdp. I was only able to test and have good results only with STATUS_ACCOUNT_DISABLED and STATUS_ACCOUNT_LOCKED_OUT.

**Comment by antenore** [comment]
Perfect, really useful. I'm merging it.

**Pull request merged**
